[project]
name = "beyond-chatgpt"
version = "0.1.0"
description = "gpt-like-a-dev"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "jupyter>=1.1.1",
    "openai",
    "pydantic>=2.11.4",
    "uvicorn>=0.34.2",
    "PyPDF2>=3.0.1",
    "numpy>=1.26.0",
    "python-dotenv>=1.0.0",
    "python-multipart>=0.0.18",
    "python-pptx>=0.6.23",
    "pytesseract>=0.3.10",
    "Pillow>=10.4.0",
    "pandas>=2.2.3",
]
